config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  get '/attention' => 'homes#attention', as: 'attention'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search' => 'searches#search', as: 'search'

  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    resources :post_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :groups do
    get 'join' => 'groups#join', as: 'join'
    resources :group_comments, only: %i[create destroy]
  end
  get 'groups/:id/member' => 'groups#member', as: 'member'

  resources :rooms, only: %i[create index show]
  resources :messages, only: [:create]

  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end

end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.includes(%i[visitor visited])
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    # 通知を全削除
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="col-md-6.mx-auto">
  <div class="form-inline">
    <div>
      <%= link_to user_path(visitor) do %>
      <%= attachment_image_tag visitor, :profile_image, :fill, 40, 40, fallback: "no-image-icon.png", class: "rounded-circle" %>
      <strong><%= visitor.name %></strong>
      <% end %>
      <%= 'さんが' %>

      <% case notification.action %>
        <% when 'follow' then %>
          <%= "あなたをフォローしました" %>

        <% when 'favorite' then %>
          <%= link_to 'あなたの投稿', post_path(visitor), style: "font-weight: bold;" %>
          <%= "にいいねしました" %>

        <% when 'post_comment' then %>
          <% if notification.post.user_id == visited.id %>
            <%= link_to "あなたの投稿", notification.post, style: "font-weight: bold;" %>
          <% else %>
            <span>
              <strong>
                <%= link_to notification.post.user.name + 'さんの投稿', post_path(visitor) %>
              </strong>
            </span>
          <% end %>
          
          <%= "にコメントしました" %>
          <p class="text-muted mb-0" >
            <%= PostComment.find_by(id: notification.post_comment_id)&.comment %>
          </p>
        <% else %>

      <% end %>
    </div>
  </div>
  <div class="small text-muted text-right">
      <%= time_ago_in_words(notification.created_at).upcase %>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
    <div class="text-center pt-4"><%= image_tag 'head/notice.gif' %></div>
    <%= link_to "", destroy_all_notifications_path, method: :delete, data: {confirm: "通知を全て消しますか？"}, class: "fas fa-trash-alt" %>
    <hr>
    <% if @notifications.exists? %>
      <div class="users-index">
        <%= render @notifications %>
      </div>
    <% else %>
      <p>通知はありません</p>
    <% end %>
    </div>
  </div>
</div>