config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  get '/attention' => 'homes#attention', as: 'attention'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search' => 'searches#search', as: 'search'

  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    resources :post_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :groups do
    get 'join' => 'groups#join', as: 'join'
    resources :group_comments, only: %i[create destroy]
  end
  get 'groups/:id/member' => 'groups#member', as: 'member'

  resources :rooms, only: %i[create index show]
  resources :messages, only: [:create]

  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end

end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :group_comments, dependent: :destroy
  
  belongs_to :user
  
  validates :name, presence: true, length: { minimum: 2 }
  validates :introduction, presence: true, length: { maximum: 50 }
  attachment :group_image, destroy: false
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit]}
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.owned_groups.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id])
    @group_comment = GroupComment.new
  end
  
  def member
    @group = Group.find(params[:id])
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to  groups_path
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end
  
  def ensure_current_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class="text-center my-4">
        <%= image_tag 'head/edit.gif' %><%= image_tag 'head/group.gif' %></div>
        <%= form_with model:@group, local:true do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, autofocus: true, class: "form-control group_name rounded-pill" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.attachment_field :group_image, class: "form-control-file group_image" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ紹介%>
          <%= f.text_area :introduction, autofocus: true, class: "form-control group_introduction rounded-pill" %>
        </div>
        <div class="form-group">
          <input type="submit" value="&#xf303; update" class="fas btn btn-sm btn-success rounded-pill">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container py-3 px-sm-0">
  <div class="row">
    <div class="col-md-3 mx-auto">
      <%= render 'users/info', user: current_user %>
    </div>
      
    <div class="col-md-8 offset-md-1 pt-3">
      <div><%= image_tag 'head/group.gif' %></div>
      <table class="table table-hover table-inverse table-striped">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
          <tr>
            <td><%= attachment_image_tag group, :group_image, :fill, 40, 40, fallback: "no-image-icon.png", class: "rounded-circle" %></td>
            <td><%= link_to group.name, group_path(group) %></td>
            <td><%= group.introduction[0..15] %></td>
            <td><i class="fas fa-gamepad"><%= group.users.count %></i></td>
            <td>
              <% if group.owner_id == current_user.id %>
                <%= link_to "", edit_group_path(group), class: "fas fa-pencil-alt" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>  
</div>

app/views/groups/member.html.erb
<div class="container py-3 px-sm-0">
  <div class="row">
    <div class="col-md-3 mx-auto">
      <%= render 'users/info', user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <div class="py-3"><%= image_tag 'head/group.gif' %><%= image_tag 'head/member.gif' %></div>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>メンバー</th>
            <th>紹介文</th>
            </tr>
        </thead>
        <tbody>
          <% @group.users.each do |member| %>
            <tr>
              <td>
                <%= attachment_image_tag member, :profile_image, :fill, 40, 40, fallback: "no-image-icon.png", class: "rounded-circle" %>
              </td>
              <td><%= link_to member.name, user_path(member.id) %></td>
              <td><%= member.introduction %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class="text-center my-4">
        <%= image_tag 'head/new.gif' %><%= image_tag 'head/group.gif' %></div>
        <%= form_with model:@group, local:true do |f| %>
         <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group">
            <%= f.label :グループ名 %>
            <%= f.text_field :name, autofocus: true, class: "form-control group_name rounded-pill" %>
          </div>
          <div class="form-group">
            <%= f.label :グループ紹介%>
            <%= f.text_area :introduction, autofocus: true, class: "form-control group_introduction rounded-pill" %>
          </div>
          <div class="form-group">
            <input type="submit" value="&#xf1d8; create" class="fas btn btn-sm btn-success rounded-pill">
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container py-3 px-sm-0">
  <div class="row">
    <div class="col-md-3 mx-auto">
      <%= render 'users/info', user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <div class="py-3"><%= image_tag 'head/group.gif' %><%= image_tag 'head/detail.gif' %></div>
      <table class="table table-hover table-inverse col-md-10">
        <tbody>
          <tr class="table-warning">
            <th>グループ名</th>
            <td><%= @group.name %></td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to "", edit_group_path(@group), class: "fas fa-pencil-alt" %>
              <% elsif @group.users.include?(current_user) %>
              <td><%= link_to 'Leave', group_path(@group), method: :delete, class: "btn btn-sm btn-danger" %></td>
              <% else %>
                <td><%= link_to 'Join', group_join_path(@group), class: "btn btn-sm btn-success" %></td>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>グループオーナー</th>
            <td><%= @group.user ? @group.user.name : "不明" %></td>
          </tr>
          <tr>
            <th>紹介文</th>
            <td><%= @group.introduction %></td>
          </tr>
          <tr>
            <th><%= link_to "メンバー一覧", member_path(@group) %></th>
            <td></td>
          </tr>
        </tbody>
      </table>
      <% if @group.users.include?(current_user) %>
        <hr/>
        <div class="pb-3"><%= image_tag 'head/comme.gif' %><%= image_tag 'head/nts.gif' %></div>
        
        <%= render 'group_comments/group_comment', group: @group %>
        <%= form_with(model:[@group, @group_comment]) do |f| %>
          <%= f.text_area :group_comment, size:"30x3" %><br>
          <div class="form-group">
            <input type="submit" value="&#xf27a; comment" class="fas btn btn-sm btn-success rounded-pill">
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>