config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  get '/attention' => 'homes#attention', as: 'attention'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search' => 'searches#search', as: 'search'

  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    resources :post_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :groups do
    get 'join' => 'groups#join', as: 'join'
    resources :group_comments, only: %i[create destroy]
  end
  get 'groups/:id/member' => 'groups#member', as: 'member'

  resources :rooms, only: %i[create index show]
  resources :messages, only: [:create]

  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 投稿機能
  has_many :posts, dependent: :destroy
  # コメント機能
  has_many :post_comments, dependent: :destroy
  # いいね機能
  has_many :favorites, dependent: :destroy

  # グループ機能
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :owned_groups, class_name: "Group"
  has_many :group_comments, dependent: :destroy

  # フォロー・フォロワー機能
  # 自分がフォローする（与フォロー側）
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  # 与フォロー関係を通じて参照する
  has_many :followings, through: :relationships, source: :followed
  # 自分はフォローされる〈被フォロー側）
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # 被フォローを通じて参照
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # DM機能
  has_many :entries, dependent: :destroy
  has_many :messeges, dependent: :destroy

  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  enum gender: { 女性: 0, 男性: 1 }

  attachment :profile_image

  # フォロー
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # フォロー通知作成メソッド
  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # バリデーション
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20, message: 'は１文字以上入力してください。' }
  validates :gender, inclusion: { in: %w(女性), message: 'は登録できません' }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit]}
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          # ルームが存在する場合
          if current.room_id == another.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      unless  @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
    @user.id = current_user.id
  end

  def update
    @user = User.find(params[:id])
    @user.id = current_user.id
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def ensure_current_user
    @user = User.find(params[:id])
    unless @user == current_user
       redirect_to user_path(current_user.id)
    end
  end
  
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_info.html.erb
  <table class="table table-hover table-inverse">
    <tbody>
      <tr>
        <div class="text-center my-2 info">
        <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 130, 130, fallback: "no-image.png", class: "rounded-lg" %>
        <% end %>
        </div>
      </tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>It's me!</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to user.followings.count, user_followings_path(user) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th> <%= link_to user.followers.count, user_followers_path(user) %></th>
      </tr>
      <tr>
        <% if user.id == current_user.id %>
          <th>setting</th>
          <th>
            <%= link_to edit_user_path(user) do %>
              <i class="btn btn-outline-secondary rounded-pill fas fa-user-cog"></i>
            <% end %>
          </th>
        <% else %>
          <% if current_user.following?(user) %>
            <th>Remove?</th>
            <th><%= link_to "", user_relationships_path(user.id), method: :delete, class: "fas fa-user-minus btn btn-primary rounded-pill" %></th>
          <% else %>
            <th>Follow?</th>
            <th><%= link_to "", user_relationships_path(user.id), method: :post, class: "fas fa-user-plus btn btn-success rounded-pill" %></th>
          <% end %>
        <% end %>
      </tr>
    </tbody>
  </table>
  <p>
    <%= link_to new_post_path do %>
            <div><%= image_tag 'memo.gif', class: "mb-3" %><%= image_tag 'new2.gif', class: "mb-3" %></div>
    <% end %>
  </p>

app/views/users/edit.html.erb
<div class="container py-3 px-sm-0">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class="text-center my-4">
        <%= image_tag 'head/edit.gif' %><%= image_tag 'head/user.gif' %></div>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="user_name">名前</label>
            <%= f.text_field :name, autofocus: true, id:"user_name", class: "form-control name rounded-pill" %>
          </div>
          <div class="form-group">
            <label for="inputImage">プロフィール画像</label>
            <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">紹介文</label>
            <%= f.text_area :introduction, autofocus: true, class: "form-control introduction rounded-pill" %>
          </div>
          <div class="form-group">
            <%= f.submit "UPDATE", class: "btn btn-secondary rounded-pill" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container py-3 px-sm-0">
  <div class="row">
    <div class="col-md-3 mx-auto">
      <%= render 'users/info', user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1 pt-3">
      <div><%= image_tag 'head/users1.gif', class: "mr-5" %>
        <%=link_to " グループを作成",new_group_path, class: 'fas fa-ghost btn btn-sm btn-success rounded-pill' %>
        | 
        <%=link_to " グループを見る",groups_path, class: 'fas fa-dragon btn btn-sm btn-info rounded-pill' %></div>
      <table class="table table-hover table-inverse table-striped">
        <thead>
          <tr>
            <th></th>
            <th>名前</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no-image-icon.png", class: "rounded-circle" %></td>
              <td><%= link_to user.name, user_path(user.id) %></td>
              <td>follows:  <%= link_to user.followings.count, user_followings_path(user) %> </td>
              <td>followers:  <%= link_to user.followers.count, user_followers_path(user) %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container py-3 px-sm-0">
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 mx-auto">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-md-8 col-lg-8 offset-md-1 pt-3">
      <h3 class="d-inline-block"><font color="#F53D14"><%= @user.name %></font><%= image_tag 'head/zu.gif'%><%= image_tag 'head/My.gif' %></h3>
        <% unless @user.id == current_user.id %>
          <% if current_user.following?(@user) && @user.following?(current_user) %>
          <% if @is_room == true %>
            <%= link_to room_path(@room_id) do %>
              <%= image_tag 'mail1.gif' %>
            <% end %>
          <% else %>
          <table>
            <tr>
              <td>
                <%= form_with model: @room, url: rooms_path, local: true do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, value: @user.id %>
                  <% end %>
                  <%= button_tag type: :submit, class: "mail" do %>
                    <%= image_tag "mail-s.gif" %>
                  <% end %>
                <% end %>
              </td>
              <td><strong>start DM</strong></td>
            </tr>
            </table>
          <% end %>
          <% end %>
      <% end %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>レビュー</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% if @posts.exists? %>
            <% @posts.each do |post| %>
              <tr>
                <td><%= attachment_image_tag post.user, :profile_image, :fill, 40, 40, fallback: "no-image-icon.png", class: "rounded-circle" %></td>
                <td><%= link_to post.title, post_path(post.id) %></td>
                <td>
                <div id="star-rate-<%= post.id %>"></div>
                <script>
                  $('#star-rate-<%= post.id %>').raty({
                    size: 36,
                    starOff: "<%= asset_path('star/off-star.gif') %>",
                    starOn: "<%= asset_path('star/on-star.gif') %>",
                    starHalf: "<%= asset_path('star/half-star.gif') %>",
                    half: true,
                    readOnly: true,
                    score: <%= post.rate %>,
                  });
                </script>
              </td>
                <td><i class="far fa-comment-alt"> <%= post.post_comments.count %></i></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td></td>
              <td>記事はありません</td>
              <td></td>
              <td></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>