config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  get '/attention' => 'homes#attention', as: 'attention'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search' => 'searches#search', as: 'search'

  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    resources :post_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :groups do
    get 'join' => 'groups#join', as: 'join'
    resources :group_comments, only: %i[create destroy]
  end
  get 'groups/:id/member' => 'groups#member', as: 'member'

  resources :rooms, only: %i[create index show]
  resources :messages, only: [:create]

  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end

end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :group_comments, dependent: :destroy
  
  belongs_to :user
  
  validates :name, presence: true, length: { minimum: 2 }
  validates :introduction, presence: true, length: { maximum: 50 }
  attachment :group_image, destroy: false
end

app/models/group_comment.rb
class GroupComment < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/group_user.rb
# frozen_string_literal: true

class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  belongs_to :room

  validates :body, presence: true, length: { maximum: 140 }
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_favorite!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id,
                               user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分自身に対するいいねは通知済みにして、通知を来ないようにする
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  # コメント通知作成メソッド
  def create_notification_comment!(current_user, post_comment_id)
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  # 検索分岐
  def self.search(word)
    where('title LIKE? OR body LIKE?', "%#{word}%", "%#{word}%")
  end

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { maximum: 300 }
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  
  validates :comment, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 投稿機能
  has_many :posts, dependent: :destroy
  # コメント機能
  has_many :post_comments, dependent: :destroy
  # いいね機能
  has_many :favorites, dependent: :destroy

  # グループ機能
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :owned_groups, class_name: "Group"
  has_many :group_comments, dependent: :destroy

  # フォロー・フォロワー機能
  # 自分がフォローする（与フォロー側）
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  # 与フォロー関係を通じて参照する
  has_many :followings, through: :relationships, source: :followed
  # 自分はフォローされる〈被フォロー側）
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # 被フォローを通じて参照
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # DM機能
  has_many :entries, dependent: :destroy
  has_many :messeges, dependent: :destroy

  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  enum gender: { 女性: 0, 男性: 1 }

  attachment :profile_image

  # フォロー
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # フォロー通知作成メソッド
  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # バリデーション
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20, message: 'は１文字以上入力してください。' }
  validates :gender, inclusion: { in: %w(女性), message: 'は登録できません' }
  validates :introduction, length: { maximum: 50 }
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="mx-auto text-center fixed-bottom" style="background: url(<%= asset_path "tree1.gif" %>);">
        <p class="text-secondary text-light pt-2">
          <%= image_tag 'gamina.gif' %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background: url(<%= asset_path "OSun.png" %>); background-size: cover;" >
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag 'header/Gamina2.gif' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon my-2"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: "mx-3" do %>
                <%= image_tag 'header/home1.gif' %>
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: "mx-3" do %>
                <%= image_tag 'header/girl.gif' %>
              <% end %>
            </li>
            <li>
              <%= link_to posts_path, class: "mx-3" do %>
                <%= image_tag 'header/book2.gif' %>
              <% end %>
            </li>
            <li>
              <%= link_to rooms_path, class: "mx-3" do %>
                <%= image_tag 'mail-s.gif' %>
              <% end %>
            </li>
            <li class="mx-3">
              <%= link_to notifications_path do %>
                <%= image_tag 'header/bell3.gif' %>
              <% end %>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle n-circle" style="color: #efa04c;"></i>
            <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, class: "mx-3", method: :delete do %>
                <%= image_tag 'header/logout2.gif' %>
              <% end %>
            </li>
            <li class="pl-3">
              <%= render 'layouts/search' %>
            </li>
            
          <% else %>
            <li>
              <%= link_to root_path, class: "mx-3" do %>
                <%= image_tag 'header/homes.gif' %>
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: "mx-3" do %>
                <%= image_tag 'header/about.gif' %>
              <% end %>
            </li>
            <li>
              <%= link_to attention_path, class: "mx-3" do %>
                <%= image_tag 'header/!.gif' %> <%= image_tag 'header/sign up.gif' %>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: "mx-3" do %>
                <%= image_tag 'header/log in.gif' %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search_form float-right">
   <%= form_with url: search_path, local: true, method: :get do |f| %>
    <div class="input-group">
     <%= f.text_field :word, class: "col-8 form-control form-control-sm rounded-pill", placeholder: "記事検索"%>
      <div class="input-group-append">
         <%= button_tag type: :submit, class: "search" do %>
         <%= image_tag 'mushi1.gif' %>
         <% end %>
      </div>
    </div>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamina</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/9ee4725604.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>